### ISSUE TITLE
快速验证支持太少了，希望官方支持更多

### ISSUE THREAD

**Issue by zhoufei666** [easy-swoole/validate#32]
比如，array ,in  inArray  , 这些都不支持，

**Comment by zhoufei666** [comment]
快速验证用的多，但是快速验证里面不支持这些就很麻烦

**Comment by chinapostm** [comment]
> 比如，array ,in inArray , 这些都不支持，

本身就支持啊 https://www.easyswoole.com/Components/Validate/validate_1.3.x.html
