### ISSUE TITLE
验证器是否支持nullable 

### ISSUE THREAD

**Issue by yhuaao** [easy-swoole/validate#33]
$rules = [
                'token'        => 'required',
                'pay_type'     => 'required|integer|between:1,3',
                'money_total'  => 'required|numeric|min:200',
                'account_type' => 'required|integer|between:1,2',
                'remark'       => 'required|lengthMax:255',
                'demand_name'  => 'required|lengthMax:255',
                'invoice_num'  => 'required|integer|max:10'
            ];

**Comment by Player626** [comment]
那你就把require去掉就行了呀

**Comment by yhuaao** [comment]
去掉了后，formdata 中若是没有设置 key信息。直接报错

**Comment by Player626** [comment]
optinal

**Comment by Player626** [comment]
你应该需要的是这个
