### ISSUE TITLE
class Validate function betweenLen bug

### ISSUE THREAD

**Issue by chuzhaoqian** [easy-swoole/validate#6]
https://github.com/easy-swoole/validate/blob/master/src/Validate.php

private function betweenLen(SplArray $splArray, string $column, $args): bool
    {
        $data = $splArray->get($column);
        $min = array_shift($args);
        $max = array_shift($args);
        if (is_numeric($data) || is_string($data)) {
            if (strlen($data) >= $min && strlen($data) <= $max) {
                return true;
            } else {
                return false;
            }
        } else if (is_array($data)) {
            if (strlen($data) >= $min && strlen($data) <= $max) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

else if (is_array($data))  判断是数据不应该使用 strlen 方法了应该使用count

**Comment by kiss291323003** [comment]
已经解决。稍后composer up即可
